-- ==========================================================
-- CAREER WEAVE: DATABASE SCHEMA
-- Target: MySQL 8.0+
-- Author: Keshav Dhanka (Lead Developer)
-- ==========================================================

-- 1. Create and Select Database
CREATE DATABASE IF NOT EXISTS career_weave_db;
USE career_weave_db;

-- 2. Users Table
-- Stores account information and hashed security credentials
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    last_visit_at TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB;

-- 3. Roadmaps Table (Parent)
-- Stores the high-level AI analysis and feasibility results
CREATE TABLE IF NOT EXISTS roadmaps (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    target_name VARCHAR(100),
    target_degree VARCHAR(150),
    career_goal VARCHAR(255) NOT NULL,
    domain VARCHAR(100),
    current_skill_level VARCHAR(100),
    skill_gap_summary TEXT,
    total_weeks INT DEFAULT 0,
    is_feasible BOOLEAN DEFAULT 1,
    is_example BOOLEAN DEFAULT 0,
    is_pinned BOOLEAN DEFAULT 0,
    feasibility_reasoning TEXT,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    last_accessed_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) 
    REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 4. Milestones Table (Child)
-- Stores the specific weekly nodes generated by the AI
CREATE TABLE IF NOT EXISTS milestones (
    id INT AUTO_INCREMENT PRIMARY KEY,
    roadmap_id INT NOT NULL,
    week_number INT NOT NULL,
    topic VARCHAR(255) NOT NULL,
    key_objective TEXT,
    task TEXT,
    difficulty VARCHAR(50), -- Beginner, Intermediate, Advanced
    estimated_hours INT,
    resources JSON,
    is_completed BOOLEAN DEFAULT 0,
    CONSTRAINT fk_roadmap FOREIGN KEY (roadmap_id) 
    REFERENCES roadmaps(id) ON DELETE CASCADE
) ENGINE=InnoDB;